# =====================================================
# ARDMS - Ansible Inventory
# =====================================================

[ardms_servers]
ardms-dev    ansible_host=YOUR_DEV_IP    ansible_user=ec2-user
ardms-staging ansible_host=YOUR_STAGING_IP ansible_user=ec2-user
ardms-prod   ansible_host=YOUR_PROD_IP   ansible_user=ec2-user

[ardms_dev]
ardms-dev

[ardms_staging]
ardms-staging

[ardms_prod]
ardms-prod

[ardms_servers:vars]
ansible_ssh_private_key_file=~/.ssh/ardms-key.pem
ansible_python_interpreter=/usr/bin/python3
