spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.ardms: INFO
    org.springframework: WARN